# Generated by Django 5.0 on 2024-04-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('P_r', models.FloatField()),
                ('Tmax_r', models.FloatField()),
                ('Tmin_r', models.FloatField()),
                ('RH_r', models.FloatField()),
                ('WS_r', models.FloatField()),
                ('SR_r', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WBMethodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('eto_method', models.SmallIntegerField(choices=[(1, 'Fao combined pm method'), (2, 'Hargreaves method'), (3, 'FAO Blaney-Cridle method'), (4, 'Makkink method'), (5, 'Hansen method'), (6, 'Modified Makkink method'), (7, 'Prestley-Taylor method')], null=True)),
                ('latitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('climate_data', models.ManyToManyField(related_name='wb_climatic_data', to='estimation.climatedatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_method_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WTFMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('catchment_area', models.FloatField()),
                ('wt_max', models.FloatField()),
                ('wt_min', models.FloatField()),
                ('num_layers', models.IntegerField()),
                ('time_period', models.FloatField()),
                ('is_precipitation_given', models.BooleanField()),
                ('precipitation_percentage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPYieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('layer_height', models.FloatField()),
                ('sp_yield_percentage', models.IntegerField()),
                ('wtf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wtf_spy_yield_data', to='estimation.wtfmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('QP_n', models.FloatField()),
                ('QB_n', models.FloatField()),
                ('Qin_n', models.FloatField()),
                ('Qout_n', models.FloatField()),
                ('Qr_n', models.FloatField()),
                ('wtf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wtf_q_data', to='estimation.wtfmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
