# Generated by Django 5.0 on 2024-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimateDataR',
            new_name='ClimateDataPMFull',
        ),
        migrations.AlterField(
            model_name='wbmethoddata',
            name='eto_method',
            field=models.SmallIntegerField(choices=[(1, 'Fao combined pm method'), (2, 'P-M (SH data)'), (3, 'FAO Blaney-Cridle method'), (4, 'Makkink method'), (5, 'Hansen method'), (6, 'Modified Makkink method'), (7, 'Prestley-Taylor method')], null=True),
        ),
    ]
