# Generated by Django 5.0 on 2024-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_rename_climatedatar_climatedatapmfull_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('P_r', models.FloatField()),
                ('Tmax_r', models.FloatField()),
                ('Tmin_r', models.FloatField()),
                ('RH_r', models.FloatField()),
                ('WS_r', models.FloatField()),
                ('SH_r', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
