# Generated by Django 5.0 on 2024-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_climatedatash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimateDataSH',
            new_name='ClimateDataPMSH',
        ),
        migrations.RemoveField(
            model_name='wbmethoddata',
            name='climate_data',
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='climate_data_full',
            field=models.ManyToManyField(related_name='wb_climatic_data_full', to='estimation.climatedatapmfull'),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='climate_data_pm_sh',
            field=models.ManyToManyField(related_name='wb_climatic_data_pm_sh', to='estimation.climatedatapmsh'),
        ),
    ]
