# Generated by Django 5.0 on 2024-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_rename_climatedatash_climatedatapmsh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('t_max', models.FloatField()),
                ('t_min', models.FloatField()),
                ('t_mean', models.FloatField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='wbmethoddata',
            name='eto_method',
            field=models.SmallIntegerField(choices=[(1, 'Fao combined pm method'), (2, 'P-M (PM_SH)'), (3, 'PM no sh and rs method'), (4, 'FAO Blaney-Criddle method'), (5, 'Makkink method'), (6, 'Hansen method'), (7, 'Modified Makkink method'), (8, 'Prestley-Taylor method')], null=True),
        ),
    ]
