# Generated by Django 5.0 on 2024-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_temperature_alter_wbmethoddata_eto_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmethoddata',
            name='temperature',
            field=models.ManyToManyField(related_name='wb_temperature', to='estimation.temperature'),
        ),
    ]
