# Generated by Django 5.0 on 2024-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_wbmethoddata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmethoddata',
            name='elevation',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='wbmethoddata',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
    ]
