# Generated by Django 5.0 on 2024-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0007_alter_wbmethoddata_elevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmethoddata',
            name='c_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
