# Generated by Django 5.0 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0008_wbmethoddata_c_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmethoddata',
            name='elevation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wbmethoddata',
            name='latitude',
            field=models.FloatField(null=True),
        ),
    ]
