# Generated by Django 5.0 on 2024-04-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0009_alter_wbmethoddata_elevation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='updated_at',
        ),
    ]
