# Generated by Django 5.0 on 2024-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0011_temperature_created_at_temperature_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmethoddata',
            name='rs_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
