# Generated by Django 5.0 on 2024-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0012_wbmethoddata_rs_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtfmethod',
            old_name='time_period',
            new_name='precipitation',
        ),
        migrations.RemoveField(
            model_name='wtfmethod',
            name='precipitation_percentage',
        ),
        migrations.AlterField(
            model_name='wbmethoddata',
            name='eto_method',
            field=models.SmallIntegerField(choices=[(1, 'Fao combined pm method'), (2, 'PM SH method)'), (3, 'PM no sh and rs method'), (4, 'FAO Blaney-Criddle method'), (5, 'Makkink method'), (6, 'Hargreaves method'), (7, 'Hansen method'), (8, 'Turc method'), (9, 'Priestly taylor method'), (10, 'Jensen haise method'), (11, 'Abtew method'), (12, 'De bruin method')], null=True),
        ),
        migrations.AlterField(
            model_name='wtfmethod',
            name='is_precipitation_given',
            field=models.BooleanField(default=True),
        ),
    ]
