# Generated by Django 5.0 on 2024-04-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0014_alter_spyielddata_sp_yield_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtfmethod',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtfmethod',
            name='yearly_recharge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
