# Generated by Django 5.0 on 2024-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0016_cropcoefficient_curvenumber_cvalue_etorsdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmethoddata',
            name='aridity_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yearly_rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yearly_recharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yearly_recharge_percentage_precipitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yearly_runoff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yearly_runoff_percentage_rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wbmethoddata',
            name='yeto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
