# Generated by Django 5.0 on 2024-04-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=150)),
                ('short_desc', models.TextField(max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_large', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_large', to='coreapp.document')),
                ('logo_small', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_small', to='coreapp.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
